ms_project/ms/urls.py
from django.conf.urls import url
from ms import views
from django.contrib import admin


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home$', views.home, name='home'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^emp$', views.emp, name='emp'),
    url(r'^empDetial/(?P<eid>[0-9]+)$', views.empDetial, name='empDetial'),
    url(r'^company$', views.company, name='company'),
    url(r'^companyDetial/(?P<cid>[0-9]+)$',views.companyDetial, name='companyDetial'),
    url(r'^projectDetial/(?P<pid>[0-9]+)$',views.projectDetial, name='projectDetial'),
    url(r'^project$', views.project, name='project'),
    url(r'^contactList/(?P<cid>[0-9]+)$',views.contactList, name='contactList'),
    url(r'^chart$', views.chart, name='chart'),
    url(r'^chartSearch$', views.chartSearch, name='chartSearch'),
    url(r'^chartDetial/(?P<cid>[0-9]+)$',views.chartDetial,name='chartDetial'),
    url(r'^sample$', views.sample, name='sample'),
    url(r'^sampleSearch$', views.sampleSearch, name='sampleSearch'),
    url(r'^sampleOfCompany/(?P<cid>[0-9]+)$', views.sampleOfCompany, name='sampleOfCompany'),
    url(r'sampleDetial/(?P<sid>[0-9]+)$', views.sampleDetial, name='sampleDetial'),
    url(r'createCompany$', views.createCompany, name='createCompany'),
    url(r'createContact$', views.createContact, name='createContact'),
    url(r'createFlower$', views.createFlower, name='createFlower'),
    url(r'createSample$', views.createSample, name='createSample'),
    url(r'createProject$', views.createProject, name='createProject'),
    url(r'createDelivery$', views.createDelivery, name='createDelivery'),
    url(r'createCotton$', views.createCotton, name='createCotton'),
    url(r'createMaterial$', views.createMaterial, name='createMaterial'),
    url(r'createEmpRecord$', views.createEmpRecord, name='createEmpRecord'),
    url(r'deliveryList$', views.deliveryList ,name='deliveryList'),
    url(r'searchDelivery$', views.searchDelivery, name='searchDelivery'),
    url(r'materialList$', views.materialList, name='materialList'),
    url(r'cottonList$', views.cottonList, name='cottonList'),
    url(r'searchMaterial$', views.searchMaterial, name='searchMaterial'),
    url(r'searchCotton$', views.searchCotton, name='searchCotton'),
    url(r'addDelivery$', views.addDelivery, name='addDelivery'),
    url(r'addMaterial$', views.addMaterial, name='addMaterial'),
    url(r'addCotton$', views.addCotton, name='addCotton'),
    url(r'outputCSV/(?P<pid>[0-9]+)$', views.outputCSV, name='outputCSV'),
    url(r'reportOfrecord$', views.recordReport, name='recordReport'),
    url(r'newrecord$',views.newrecord, name='newrecord'),
    url(r'sendmail',views.sendmail, name='sendmail')

]

ms_project/ms_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/',admin.site.urls, name='admin'),
    url(r'^ms/', include('ms.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ms_project/ms/models.py
from django.db import models
import time

# 客户
class Company(models.Model):
    name = models.CharField('公司名称', max_length=30)
    address = models.CharField('公司地址', max_length=50, blank=True)
    phone = models.CharField('联系电话', max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '客户'
        verbose_name_plural = verbose_name
        ordering = ['-name']


# 联系人
class Contact(models.Model):
    name = models.CharField('姓名', max_length=20)
    phone = models.CharField('电话', max_length=20)
    email = models.EmailField('邮箱', blank=True)
    company = models.ForeignKey(Company,verbose_name='公司名称', on_delete=models.CASCADE,)

    def __str__(self):
        return u'%s - %s' % (self.company.name, self.name)

    class Meta:
        verbose_name = '联系人'
        verbose_name_plural = verbose_name
        ordering = ['-company']


# 花型
class Flower(models.Model):
    name = models.CharField(verbose_name='花型名称',max_length=50)
    comment = models.CharField(verbose_name='备注',max_length=100, blank=True)
    image = models.ImageField(verbose_name='图形样例',upload_to='uploads/ms/flowers/', blank=True)  # 图片样例
    dstfile = models.FileField(verbose_name='制图文件',upload_to='uploads/ms/flowers/DST', blank=True) # 制图文件

    def __str__(self):
        return u'%s' % (self.name)

    def fileName(self):
        return self.dstfile.__str__().split('/')[-1]

    fileName.short_description = '文件名'

    class Meta:
        verbose_name = '花型'
        verbose_name_plural = verbose_name
        ordering = ['-name']


# 项目
class Project(models.Model):
    company = models.ForeignKey(Company, verbose_name='公司名称', on_delete=models.CASCADE,)
    contact = models.ManyToManyField(Contact, verbose_name='项目联系人',)
    name = models.CharField(verbose_name='项目名称', max_length=30)
    createDate = models.DateField(verbose_name='创建时间')
    finishDate = models.DateField(verbose_name='完成时间', blank=True, null= True)
    image = models.ImageField(verbose_name='原文件', upload_to='uploads/ms/projects/project/', blank=True)
    flower = models.ForeignKey(Flower, verbose_name='花型', blank=True, null= True,default='')
    isFinish = models.CharField(verbose_name='进度', max_length=1, choices=(('0', '未完成'), ('1', '完成'),), default='0')
    isClose = models.CharField(verbose_name='结算', max_length=1, choices=(('0', '未结算'), ('1', '已结算'),), default='0')
    comment = models.CharField(max_length=100,verbose_name='备注', blank=True)


    def strCreateDate(self):
        strDate = self.createDate.strftime('%Y-%m-%d')
        return strDate

    def __str__(self):
        return u'%s - %s' % (self.company.name, self.name)

    class Meta:
        verbose_name = '项目'
        verbose_name_plural = verbose_name
        ordering = ['-company']


# 布料
class Material(models.Model):
    project = models.ForeignKey(Project,verbose_name='项目名称', on_delete=models.CASCADE,)
    # 缸号
    num = models.CharField(verbose_name='缸号',max_length=10, blank=True, default='无')
    # 颜色
    color = models.CharField(verbose_name='颜色',max_length=10)
    # 米数
    length = models.FloatField(verbose_name='米数')
    # 入库时间
    inTime = models.DateField(verbose_name='入库时间', blank=True, null= True)
    image = models.ImageField(verbose_name='原文件', upload_to='uploads/ms/projects/material/', blank=True)  # 原始项目文件
    # 备注
    comment = models.CharField(verbose_name='备注',max_length=100, blank=True)


    def __str__(self):
        return u'%s - %s : 缸号[ %s ], 颜色[ %s ], 米数[ %s ]' % (self.project.company.name, self.project.name, self.num, self.color, self.length)

    class Meta:
        verbose_name = '布料'
        verbose_name_plural = verbose_name
        ordering = ['-project']


# 棉
class Cotton(models.Model):
    project = models.ForeignKey(Project, verbose_name='项目名称', on_delete=models.CASCADE,)
    # 类型
    name = models.CharField(verbose_name='类型', max_length=10)
    # 重量
    weight = models.IntegerField(verbose_name='重量')
    # 宽度
    width = models.FloatField(verbose_name='宽度', blank=True , default='1.5')
    # 米数
    length = models.FloatField(verbose_name='米数', blank=True)
    # 入库时间
    inTime = models.DateField(verbose_name='入库时间', blank=True, null= True)
    image = models.ImageField(verbose_name='原文件', upload_to='uploads/ms/projects/cotton/', blank=True)  # 原始项目文件
    # 备注
    comment = models.CharField(verbose_name='备注', max_length=100, blank=True)

    def strName(self):
        strname = self.name+' : '+str(self.weight)+' g'
        return strname

    strName.short_description = '棉名称'

    def __str__(self):
        return u'%s - %s | %s - %s ' % (self.name, self.weight, self.project.name, self.project.company.name)

    class Meta:
        verbose_name = '棉'
        verbose_name_plural = verbose_name
        ordering = ['-project']


# 机器
class Machine(models.Model):
    name = models.CharField(verbose_name='机器名称', max_length=15)
    # 前后距离 1-2
    step_1_2 = models.FloatField(verbose_name='前后间距-1')
    # 前后距离 2-3
    step_2_3 = models.FloatField(verbose_name='前后间距-2')
    # 左右两针间隔距离
    space = models.FloatField(verbose_name='左右间距')

    def __str__(self):
        return self.name + '[ ' + str(self.step_1_2) + " - " + str(self.step_2_3) + ' - ' + str(self.space) + ' ]'

    class Meta:
        verbose_name = '机器'
        verbose_name_plural = verbose_name
        ordering = ['-name']


# 员工
class Emp(models.Model):
    name = models.CharField(verbose_name='姓名', max_length=10)
    phone = models.CharField(verbose_name='电话', max_length=15, blank=True)
    address = models.CharField(verbose_name='地址', max_length=50, blank=True)
    joinDate = models.DateField(verbose_name='入职时间', blank=True, null= True)
    leaveDate = models.DateField(verbose_name='离职时间', blank=True, null= True)
    comment = models.CharField(verbose_name='备注', max_length=100, blank=True)
    onduty = models.CharField(verbose_name='状态', max_length=1, choices=(('0', '离职'), ('1', '在职'),),default='1')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '员工'
        verbose_name_plural = verbose_name
        ordering = ['-name']


class Delivery(models.Model):
    project = models.ForeignKey(Project, verbose_name='项目', on_delete=models.CASCADE,)
    # 缸号
    num = models.CharField(verbose_name='缸号',max_length=10, blank=True, default='无')
    # 颜色
    color = models.CharField(verbose_name='颜色',max_length=10, blank=True, null=True)
    length = models.FloatField(verbose_name='送出米数', blank=True, null=True)
    outDate = models.DateField(verbose_name='发货日期', blank=True, null=True)
    image = models.ImageField(verbose_name='发货单', upload_to='uploads/ms/projects/delivery/', blank=True)  # 原始项目文件
    comment = models.CharField(verbose_name='备注', max_length=100, blank=True)


    def __str__(self):
        return u'%s - %s (缸号：%s, 颜色: %s) ' %(self.project.company.name, self.project.name, self.num, self.color)

    class Meta:
        verbose_name = '出货单'
        verbose_name_plural = verbose_name
        ordering = ['-outDate']


class Record(models.Model):
    emp = models.ForeignKey(Emp, verbose_name='员工', on_delete=models.CASCADE)
    inTime = models.DateTimeField(verbose_name='上班时间', blank=True, null= True)
    outTime = models.DateTimeField(verbose_name='下班时间', blank=True, null=True)
    project = models.ForeignKey(Project, verbose_name='项目', default='')
    produce = models.FloatField(verbose_name='日产量',default=0.0)
    comment = models.CharField(verbose_name='备注', max_length=100, blank=True)

    def strInTime(self):
        strDate = self.inTime.strftime('%Y-%m-%d  %H:%m')
        return strDate

    strInTime.short_description = '上班时间'

    def strOutTime(self):
        strDate = self.outTime.strftime('%Y-%m-%d  %H:%m')
        return strDate

    strOutTime.short_description = '下班时间'

    def workDate(self):
        strDate = self.inTime.strftime('%Y-%m-%d')
        return strDate

    workDate.short_description = '工作日期'

    def workHour(self):
        hour = float((self.outTime - self.inTime).seconds / 3600)
        return hour

    workHour.short_description = '工作时长'

    def __str__(self):
        return u'%s [ %s ] 工作时长: %d 小时' % (self.emp.name, self.workDate(), self.workHour())

    class Meta:
        verbose_name = '考勤记录'
        verbose_name_plural = verbose_name
        ordering = ['-inTime']


class SampleMap(models.Model):
    flower = models.ForeignKey(Flower, verbose_name='花型', blank=True, null=True, default='')
    # 颜色
    color = models.CharField(verbose_name='颜色',max_length=10)
    # 米数
    length = models.FloatField(verbose_name='米数')
    # 类型
    cottonName = models.CharField(verbose_name='类型', max_length=10)
    # 重量
    cottonWeight = models.IntegerField(verbose_name='重量')

    machine = models.ForeignKey(Machine, verbose_name='加工机器', on_delete=models.CASCADE, blank=True, null=True, default='')

    comment = models.CharField(max_length=100, verbose_name='备注', blank=True)

    def __str__(self):
        return u'花型：%s , %s 布料 %s 米, %s %s 克 - 机器：%s' % (self.flower.name, self.color, self.length, self.cottonName, self.cottonWeight, self.machine.name)

    class Meta:
        verbose_name = '加工原料'
        verbose_name_plural = verbose_name
        ordering = ['flower']


    # 打样
class Sample(models.Model):
    company = models.ForeignKey(Company, verbose_name='公司名称', on_delete=models.CASCADE, )
    contact = models.ManyToManyField(Contact, verbose_name='项目联系人', )
    name = models.CharField(verbose_name='项目名称', max_length=30)
    createDate = models.DateField(verbose_name='创建时间')
    image = models.ImageField(verbose_name='原文件', upload_to='uploads/ms/projects/sample/', blank=True)
    sampleMap = models.ManyToManyField(SampleMap, verbose_name='加工原料',)
    comment = models.CharField(max_length=100, verbose_name='备注', blank=True)

    def __str__(self):
        return u'%s - %s' % (self.company.name, self.name)

    class Meta:
        verbose_name = '打样'
        verbose_name_plural = verbose_name

ms_project/ms/templates/chart.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% include 'ms/head.html' %}
    <title>莫氏绗缝绣饰中心管理系统 - 制图</title>
</head>
<body class="f6">
{% include 'ms/nav.html' %}
{% include 'ms/chartSearch.html' %}
</body>
</html>

ms_project/ms/templates/chartDetial.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% include 'ms/head.html' %}{% load staticfiles %}
    <title>莫氏绗缝绣饰中心管理系统 - 花型详情</title>
    <style>
        #table td,th{
            vertical-align:middle;
            text-align:center;
        }
    </style>
</head>
<body class="f6">
{% include 'ms/nav.html' %}

<div class="panel-info">
    <div class="panel-heading">
        <span>花型名称： </span>{{ chart.name }}
    </div>
    <div class="panel-body">
        <div class="row" style="height: 230px;">
            <div class="col-md-2">
                        {% if chart.image %}
                            <a href="{{ chart.image.url }}" class="thumbnail" style="width: 171px;height: 180px;">
                            <img src="{{ chart.image.url }}"  alt="项目原文件" style="width: 171px;height: 180px;">
                            </a>
                        {% endif %}
                        {% if not chart.image %}
                            <img src="{% static "img/hold.png" %}"  alt="项目原文件" style="width: 171px;height: 180px;">
                        {% endif %}
            </div>
            <div class="col-md-3">
                <table class="table table-hover">
                    <tr>
                        <th style="vertical-align:middle; text-align:center;">名称</th>
                        <td style="vertical-align:middle; text-align:center;">{{ chart.name }}</td>

                    </tr>
                    <tr>
                        <th style="vertical-align:middle; text-align:center;">文件</th>
                        <td style="vertical-align:middle; text-align:center;">
                            {% if chart.dstfile %}
                            <a href="/media/{{ chart.dstfile }}">{{ chart.fileName }}</a>
                            {% else %}
                            <a href="">缺少文件</a>
                            {% endif %}
                        </td>

                    </tr>
                    <tr>
                        <th style="vertical-align:middle; text-align:center;">备注</th>
                        <td style="vertical-align:middle; text-align:center;">
                            {% if chart.comment|length > 8 %}
                                <span id="comment" data-toggle="tooltip" data-placement="bottom" title="{{ chart.comment}}">{{ chart.comment|slice:"8"}}...</span>
                            {% else %}
                                {{ chart.comment}}
                            {% endif %}</td>

                    </tr>
                </table>
            </div>
            <div class="col-md-7" style="height: 230px;">
                <div class="panel-success" style="height: 230px;">
                    <div class="panel-heading">
                        <span>关联项目列表 </span><span class="label label-success">{{ projectList|length }}</span>
                    </div>
                    <div class="panel-body pre-scrollable" style="height: 180px;">
                        <table class="table table-hover">
                            <thead>
                                <th>日期</th><th>公司</th><th>项目</th><th>联系人</th>
                            </thead>
                            <tbody>
                            {% for p in projectList %}
                                <tr>
                                    <td>{{ p.createDate|date:'Y/m/d' }}</td>
                                    {% url 'companyDetial' p.company.id as  companyDetial_url%}
                                    <td><a href="{{ companyDetial_url }}">{{ p.company.name }}</a></td>
                                    {% url 'projectDetial' p.id as  projectDetial_url%}
                                    <td><a href="{{ projectDetial_url }}">{{ p.name }}</a></td>
                                    <td><span title="联系电话： {{ p.contact.first.phone }}">{{ p.contact.first.name }}</span></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="panel-info">
                <div class="panel-heading">
                    相关打样列表 <span class="label label-success"> {{ sample_list|length }}</span>
                </div>
                <div class="panel-body pre-scrollable" id="table">
                    <table class="table table-hover">
                    <thead>
                    <th>编号</th><th>日期</th><th>公司</th><th>名称</th><th>联系人</th><th>加工方式</th>
                    </thead>
                    {% for s in sample_list %}
                        <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ s.createDate|date:'Y年m月d日' }}</td>
                        <td>{% url 'sampleOfCompany' s.company.id as sc_url %}
                            <a href="{{ sc_url }}">{{ s.company.name }}</a></td>
                        <td>{% url 'sampleDetial' s.id as sd_url %}
                        <a href="{{ sd_url }}">{{ s.name }}</a>
                        </td>
                        <td>{{ s.contact.first.name }}</td>
                        <td>
                            <table class="table table-hover">
                                        <tbody>
                                            {% for sm in s.sampleMap.all %}
                                            <tr>
                                                <th>花型</th>
                                                {% url 'chartDetial' sm.flower.id as sf_url %}
                                                <td><a href="{{ sf_url }}">{{ sm.flower.name }}</a></td>
                                                <th>棉类型</th>
                                                <td>{{ sm.cottonName }} | {{ sm.cottonWeight }} g</td>
                                                <th>加工机器</th>
                                                <td>{{ sm.machine.name }}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                            </table>
                        </td>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
<script>
    $('#comment').tooltip('toggle')
</script>
</body>
</html>

ms_project/ms/templates/company.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% include 'ms/head.html' %}

    <title>莫氏绗缝绣饰中心管理系统 - 客户</title>
</head>
<body class="f4">
{% include 'ms/nav.html' %}
<div class="panel panel-primary" style="height: 500px;">
  <div class="panel-heading">客戶列表</div>
  <div class="panel-body" >
	<div class="row ">
        <div class="col-md-3 column pre-scrollable">
		{% include 'ms/companyList.html' %}
        </div>
		<div class="col-md-9 column">
            <div class="row ">
            {% include 'ms/projectSearch.html' %}
            </div>
            <div class="row ">
                <div class="col-md-12 column pre-scrollable">
                    <table class="table table-hover">
                        <thead>
                            <th>公司名称</th><th>项目名称</th><th>创建时间</th><th>项目联系人</th><th>项目进度</th><th>结算进度</th><th>备注</th>
                        </thead>
                        {% for project in project_list %}
                                <tr>
                                    {% url 'companyDetial' project.company.id as company_url_1 %}
                                <td><a href='{{ company_url_1}}'>{{ project.company.name }}</a></td>
                                    {% url 'projectDetial' project.id as projectDetial_url %}
                                <td><a href="{{ projectDetial_url }}">{{ project.name }}</a></td>
                                <td>{{ project.createDate|date:'Y年m月d日' }}</td>
                                <td><span title="电话: {{ project.contact.first.phone }}"> {{ project.contact.first.name }} </span>
                                </td>
                                <td>{{ project.get_isFinish_display }}</td><td>{{ project.get_isClose_display }}</td>
                                    {% if project.comment|length > 8 %}
                                        <td><span title="{{ project.comment}}">{{ project.comment|slice:"8"}}...</span></td>
                                    {% else %}
                                        <td>{{ project.comment}}</td>
                                    {% endif %}

                            </tr>
                        {% endfor %}

                    </table>
                </div>

            </div>

		</div>
	</div>
  </div>
</div>
<script>
     $('input').attr('autocomplete','off')
</script>
</body>
</html>

ms_project/ms/templates/emp_detial.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% include 'ms/head.html' %}
    <title>莫氏绗缝绣饰中心管理系统 - 员工信息</title>
</head>
<body class="f5">
{% include 'ms/nav.html' %}
{% include  'ms/empDetial.html'%}
</body>
</html>

ms_project/ms/templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
        {% include 'ms/head.html' %}
		<title>莫氏绗缝绣饰中心管理系统</title>
        <style>
            .form-signin{
                max-width: 390px;
                padding: 15px;
                padding-top: 100px;
                margin: 0 auto;
            }
            .head{
                width: 100%;
                margin-bottom: 10px;
            }
        </style>
	</head>
	<body>
	<div class="container-fluid">

		<div id="form_action">
			<form action="login" class="form-signin" role="form" method="post">
                <div class="btn btn-primary btn-lg active head">莫氏绗缝绣饰中心管理系统</div>
				<div class="form-group">
    				<input type="text" class="form-control" name="name" id="name" placeholder="用户名" required>
  				</div>
  				<div class="form-group">
    				<input type="password" class="form-control" name="password" id="password" placeholder="密码" required>
  				</div>
			<center><button type="submit" class="btn btn-primary" style="">登陆</button></center>
			
			</form>
		</div>
	</div>
	</body>
</html>

ms_project/ms/templates/myBase.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% include 'ms/head.html' %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
<style>
    td,th{
        vertical-align:middle;
        text-align:center;
    }

</style>
<script>
     $('input').attr('autocomplete','off')
</script>
</head>
<body>
{% load mytags %}
{% include 'ms/nav.html' %}

{% block context %}
{% endblock %}

</body>
</html>

ms_project/ms/templates/project.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% include 'ms/head.html' %}
    <title>莫氏绗缝绣饰中心管理系统 - 项目</title>
</head>
<body class="f3">
{% include 'ms/nav.html' %}
<div class="panel panel-primary">
    <div class="panel-heading">
        项目列表 - 剩余项目量：{{ notFinishedProjects|length }} 个 - 剩余项目总米数：{{ sumLength }} 米
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12 column">
                <div class="row">
                    <div class="col-md-2 column">
                    </div>
                    <div class="col-md-8 column">
                        {% include 'ms/projectSearch.html' %}
                    </div>
                    <div class="col-md-2 column">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 column">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                未完成项目  <span class="label label-info">{{ notFinishedProjects|length }}</span>
                            </div>
                            <div class="panel-body pre-scrollable">
                                <table class="table table-hover">
                                    <thead>
                                    <th>日期</th><th>公司</th><th>项目</th>
                                    </thead>
                                    <tbody>
                                    {% for e in notFinishedProjects %}
                                        <tr>{% url 'projectDetial' e.id as project_detial_url%}
                                            {% url 'companyDetial' e.company.id as company_detial_url%}
                                        <td>{{ e.createDate|date:'Y/m/d' }}</td>
                                            <td><a href="{{ company_detial_url }}">{{ e.company.name }}</a></td>
                                        <td><a href="{{ project_detial_url }}">{{ e.name }}</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 column">
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                已完成 - 未结算项目  <span class="label label-warning">{{ notClosedProjects|length }}</span>
                            </div>
                            <div class="panel-body pre-scrollable">
                                <table class="table table-hover">
                                    <thead>
                                    <th>日期</th><th>公司</th><th>项目</th>
                                    </thead>
                                    <tbody>
                                    {% for e in notClosedProjects %}
                                        <tr>{% url 'projectDetial' e.id as project_detial_url%}
                                            {% url 'companyDetial' e.company.id as company_detial_url%}
                                        <td>{{ e.createDate|date:'Y/m/d' }}</td>
                                            <td><a href="{{ company_detial_url }}">{{ e.company.name }}</a></td>
                                        <td><a href="{{ project_detial_url }}">{{ e.name }}</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 column">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                已结算项目  <span class="label label-success">{{ closedProjects|length }}</span>
                            </div>
                            <div class="panel-body pre-scrollable">
                                <table class="table table-hover">
                                    <thead>
                                    <th>日期</th><th>公司</th><th>项目</th>
                                    </thead>
                                    <tbody>
                                    {% for e in closedProjects %}
                                        <tr>{% url 'projectDetial' e.id as project_detial_url%}
                                            {% url 'companyDetial' e.company.id as company_detial_url%}
                                        <td>{{ e.createDate|date:'Y/m/d' }}</td>
                                            <td><a href="{{ company_detial_url }}">{{ e.company.name }}</a></td>
                                        <td><a href="{{ project_detial_url }}">{{ e.name }}</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 column">
                <div class="panel panel-primary">
                    <div class="panel-body pre-scrollable">
                        <table class="table table-hover">
                            <thead>
                                <th>创建时间</th><th>公司名称</th><th>项目名称</th><th>项目状态</th>
                            </thead>
                            <tbody>
                                {% for project in project_list %}
                                    {% url 'projectDetial' project.id as project_detial_url%}
                                    <tr>
                                        <td>{{ project.createDate|date:'Y-m-d' }}</td>
                                        <td>{{ project.company.name }}</td>
                                        <td><a href="{{ project_detial_url }}" title="{{ project.company.name }}">{{ project.name }}</a></td>
                                        <td>{{ project.get_isFinish_display }} | {{ project.get_isClose_display }}</td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
     $('input').attr('autocomplete','off')
</script>
</body>
</html>